var titles = [
    "have a good weekend",
    "trolled, honestly",
    "TROLLED!!",
    "flameband was here",
    "have you seen fries.pics?",
    "ajnin.snivelbrelyt",
    "tylerblevins.ninja",
    "nfts coming never",
    "have you heard of trollcoin?",
    "a life before covid",
    "a troll before trolling",
    "the original little funny guy",
    "opion 1",
    "help i made this against my will",
    "unpaid and unlaid",
    "yo look at this cool moth i found",
    "god has abandoned us",
    "ninja mixer fortnite!",
    "pretend this is funny",
    "minecraft dirt block",
    "merry trollmas",
    "fuck you",
    "have you heard of among us?",
    "exmonochrome",
    "sksksksksks",
    "dying light 2, feb 4 2022",
    "trans rights",
    "are you gay? take  this funny quiz!",
    "he stares in to my soul and I like it",
    "i kissed a girl and i liked it",
    "⚧️",
    "( ͡° ͜ʖ ͡°)",
    "2b2t",
    "watch a silent voice, it's good",
    "drgonzophd is not safe",
    "firefox crypto D:",
    "awooga!",
    "© tylar blivin",
    "oh no, our table!",
    "the phrase it's just a game...",
    "a sandwich (not asked for)",
    "the fuck did you just say to me?",
    "you kiss your mother with that mouth?",
    "you shut that mouth",
    "i am trained in gorilla warfare",
    "nya~!",
    "catboy ninja",
    "thanks for the gold kind stranger",
    "alchemist by good kid",
    "i eat paint",
    "glue sniffer",
    "thans for ip!!!",
    "twitter.com machine",
    "fnaf used to be good",
    "politics",
    "mommy, sorry, mommy, sorry...",
    "sorry that last one wasnt funny",
    "gweilo government",
    "zhang yong!!",
    "waste of money",
    "i love ultrakill",
    "roblox bad, minecraft good",
    "csgo gambling!",
    "cringe",
    "terrorism = advanced trolling",
    "minecraft griefing"
];

var randomItem = titles[Math.floor(Math.random()*titles.length)];
document.title = randomItem