var titles = [
    "have a good weekend",
    "trolled, honestly",
    "TROLLED!!",
    "flameband was here",
    "have you seen fries.pics?",
    "ajnin.snivelbrelyt",
    "tylerblevins.ninja",
    "nfts coming never",
    "have you heard of trollcoin?",
    "a life before covid",
    "a troll before trolling",
    "the original little funny guy",
    "opion 1",
    "help i made this against my will",
    "unpaid and unlaid",
    "yo look at this cool moth i found",
    "god has abandoned us",
    "ninja mixer fortnite!",
    "pretend this is funny",
    "minecraft dirt block",
    "merry trollmas",
    "fuck you",
    "have you heard of among us?",
    "exmonochrome",
    "sksksksksks",
    "dying light 2, feb 4 2022",
    "trans rights",
    "are you gay? take  this funny quiz!",
    "he stares in to my soul and I like it",
    "i kissed a girl and i liked it",
    "⚧️",
    "( ͡° ͜ʖ ͡°)",
    "2b2t",
    "watch a silent voice, it's good",
    "drgonzophd is not safe",
    "firefox crypto D:",
    "awooga!",
    "© tylar blivin",
    "oh no, our table!"
];

var randomItem = titles[Math.floor(Math.random()*titles.length)];
document.title = randomItem